### ISSUE TITLE
Mention container name in logs.

### ISSUE THREAD

**Issue by gsavelev** [sklyar/docker-log-driver-telegram#1]
Is it possible to add container name, from which the message is coming, to log message?

**Comment by sklyar** [comment]
Yes, it's possible. You can add the "container_name" varibale to the log template option. For example:

```bash
docker run --log-driver=telegram \
    --log-opt token="<bot_token>" \
    --log-opt chat_id="<chat_id>" \
    --log-opt template="{container_name}: {log}"
```
Also, check out [other tags](https://github.com/sklyar/docker-log-driver-telegram/blob/main/logger.go#L175C16-L175C16) for additional options.

**Comment by gsavelev** [comment]
@sklyar, could you please give correct example of using `template` directive in _compose.yml_?

**Comment by sklyar** [comment]
@gsavelev, I apologize for the mistake in my previous response. The correct format for the template directive should indeed use single curly braces and no dot. I will update the documentation accordingly.

To add the container name to the log message using Docker Compose, you can use the following configuration:

```yaml
version: '3.8'

services:
  my_service:
    image: your/image
    logging:
      driver: telegram
      options:
        token: "<bot_token>"
        chat_id: "<chat_id>"
        template: "{container_name}: {log}"

```
